import React from 'react';

const Home = () => {
    return (
        <div>
            <div className=' pt-20 bg-red-200' id='home'>
            <h2 className='text-5xl font-bold'>Home Page</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique error sint ullam et recusandae ex sapiente! Sit neque atque quisquam tempora dolorum praesentium. Laborum quibusdam voluptatum ipsum exercitationem recusandae, labore quod esse dolor cumque perspiciatis qui laudantium odio hic obcaecati, maiores velit ex unde, earum commodi? Expedita cumque dignissimos fuga libero sed dolorum nesciunt beatae deserunt, recusandae voluptatibus ratione doloremque repudiandae amet nisi dolor. Dolorum quo obcaecati ratione molestias dicta minima accusantium error sit libero! Dolores aut temporibus quibusdam iure deserunt dicta at perferendis exercitationem hic totam quae qui reiciendis sint quos repudiandae, accusantium repellendus voluptates consequatur tenetur animi blanditiis!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique error sint ullam et recusandae ex sapiente! Sit neque atque quisquam tempora dolorum praesentium. Laborum quibusdam voluptatum ipsum exercitationem recusandae, labore quod esse dolor cumque perspiciatis qui laudantium odio hic obcaecati, maiores velit ex unde, earum commodi? Expedita cumque dignissimos fuga libero sed dolorum nesciunt beatae deserunt, recusandae voluptatibus ratione doloremque repudiandae amet nisi dolor. Dolorum quo obcaecati ratione molestias dicta minima accusantium error sit libero! Dolores aut temporibus quibusdam iure deserunt dicta at perferendis exercitationem hic totam quae qui reiciendis sint quos repudiandae, accusantium repellendus voluptates consequatur tenetur animi blanditiis!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique error sint ullam et recusandae ex sapiente! Sit neque atque quisquam tempora dolorum praesentium. Laborum quibusdam voluptatum ipsum exercitationem recusandae, labore quod esse dolor cumque perspiciatis qui laudantium odio hic obcaecati, maiores velit ex unde, earum commodi? Expedita cumque dignissimos fuga libero sed dolorum nesciunt beatae deserunt, recusandae voluptatibus ratione doloremque repudiandae amet nisi dolor. Dolorum quo obcaecati ratione molestias dicta minima accusantium error sit libero! Dolores aut temporibus quibusdam iure deserunt dicta at perferendis exercitationem hic totam quae qui reiciendis sint quos repudiandae, accusantium repellendus voluptates consequatur tenetur animi blanditiis!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique error sint ullam et recusandae ex sapiente! Sit neque atque quisquam tempora dolorum praesentium. Laborum quibusdam voluptatum ipsum exercitationem recusandae, labore quod esse dolor cumque perspiciatis qui laudantium odio hic obcaecati, maiores velit ex unde, earum commodi? Expedita cumque dignissimos fuga libero sed dolorum nesciunt beatae deserunt, recusandae voluptatibus ratione doloremque repudiandae amet nisi dolor. Dolorum quo obcaecati ratione molestias dicta minima accusantium error sit libero! Dolores aut temporibus quibusdam iure deserunt dicta at perferendis exercitationem hic totam quae qui reiciendis sint quos repudiandae, accusantium repellendus voluptates consequatur tenetur animi blanditiis!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique error sint ullam et recusandae ex sapiente! Sit neque atque quisquam tempora dolorum praesentium. Laborum quibusdam voluptatum ipsum exercitationem recusandae, labore quod esse dolor cumque perspiciatis qui laudantium odio hic obcaecati, maiores velit ex unde, earum commodi? Expedita cumque dignissimos fuga libero sed dolorum nesciunt beatae deserunt, recusandae voluptatibus ratione doloremque repudiandae amet nisi dolor. Dolorum quo obcaecati ratione molestias dicta minima accusantium error sit libero! Dolores aut temporibus quibusdam iure deserunt dicta at perferendis exercitationem hic totam quae qui reiciendis sint quos repudiandae, accusantium repellendus voluptates consequatur tenetur animi blanditiis!</p>
        </div>
        <div className=' pt-20 bg-yellow-300' id='about'>
            <h2 className='text-5xl font-bold'>About</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique error sint ullam et recusandae ex sapiente! Sit neque atque quisquam tempora dolorum praesentium. Laborum quibusdam voluptatum ipsum exercitationem recusandae, labore quod esse dolor cumque perspiciatis qui laudantium odio hic obcaecati, maiores velit ex unde, earum commodi? Expedita cumque dignissimos fuga libero sed dolorum nesciunt beatae deserunt, recusandae voluptatibus ratione doloremque repudiandae amet nisi dolor. Dolorum quo obcaecati ratione molestias dicta minima accusantium error sit libero! Dolores aut temporibus quibusdam iure deserunt dicta at perferendis exercitationem hic totam quae qui reiciendis sint quos repudiandae, accusantium repellendus voluptates consequatur tenetur animi blanditiis!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique error sint ullam et recusandae ex sapiente! Sit neque atque quisquam tempora dolorum praesentium. Laborum quibusdam voluptatum ipsum exercitationem recusandae, labore quod esse dolor cumque perspiciatis qui laudantium odio hic obcaecati, maiores velit ex unde, earum commodi? Expedita cumque dignissimos fuga libero sed dolorum nesciunt beatae deserunt, recusandae voluptatibus ratione doloremque repudiandae amet nisi dolor. Dolorum quo obcaecati ratione molestias dicta minima accusantium error sit libero! Dolores aut temporibus quibusdam iure deserunt dicta at perferendis exercitationem hic totam quae qui reiciendis sint quos repudiandae, accusantium repellendus voluptates consequatur tenetur animi blanditiis!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique error sint ullam et recusandae ex sapiente! Sit neque atque quisquam tempora dolorum praesentium. Laborum quibusdam voluptatum ipsum exercitationem recusandae, labore quod esse dolor cumque perspiciatis qui laudantium odio hic obcaecati, maiores velit ex unde, earum commodi? Expedita cumque dignissimos fuga libero sed dolorum nesciunt beatae deserunt, recusandae voluptatibus ratione doloremque repudiandae amet nisi dolor. Dolorum quo obcaecati ratione molestias dicta minima accusantium error sit libero! Dolores aut temporibus quibusdam iure deserunt dicta at perferendis exercitationem hic totam quae qui reiciendis sint quos repudiandae, accusantium repellendus voluptates consequatur tenetur animi blanditiis!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique error sint ullam et recusandae ex sapiente! Sit neque atque quisquam tempora dolorum praesentium. Laborum quibusdam voluptatum ipsum exercitationem recusandae, labore quod esse dolor cumque perspiciatis qui laudantium odio hic obcaecati, maiores velit ex unde, earum commodi? Expedita cumque dignissimos fuga libero sed dolorum nesciunt beatae deserunt, recusandae voluptatibus ratione doloremque repudiandae amet nisi dolor. Dolorum quo obcaecati ratione molestias dicta minima accusantium error sit libero! Dolores aut temporibus quibusdam iure deserunt dicta at perferendis exercitationem hic totam quae qui reiciendis sint quos repudiandae, accusantium repellendus voluptates consequatur tenetur animi blanditiis!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique error sint ullam et recusandae ex sapiente! Sit neque atque quisquam tempora dolorum praesentium. Laborum quibusdam voluptatum ipsum exercitationem recusandae, labore quod esse dolor cumque perspiciatis qui laudantium odio hic obcaecati, maiores velit ex unde, earum commodi? Expedita cumque dignissimos fuga libero sed dolorum nesciunt beatae deserunt, recusandae voluptatibus ratione doloremque repudiandae amet nisi dolor. Dolorum quo obcaecati ratione molestias dicta minima accusantium error sit libero! Dolores aut temporibus quibusdam iure deserunt dicta at perferendis exercitationem hic totam quae qui reiciendis sint quos repudiandae, accusantium repellendus voluptates consequatur tenetur animi blanditiis!</p>
        </div>
        <div className=' pt-20 bg-gray-300' id='portfolio'>
            <h2 className='text-5xl font-bold'>Portfolio</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique error sint ullam et recusandae ex sapiente! Sit neque atque quisquam tempora dolorum praesentium. Laborum quibusdam voluptatum ipsum exercitationem recusandae, labore quod esse dolor cumque perspiciatis qui laudantium odio hic obcaecati, maiores velit ex unde, earum commodi? Expedita cumque dignissimos fuga libero sed dolorum nesciunt beatae deserunt, recusandae voluptatibus ratione doloremque repudiandae amet nisi dolor. Dolorum quo obcaecati ratione molestias dicta minima accusantium error sit libero! Dolores aut temporibus quibusdam iure deserunt dicta at perferendis exercitationem hic totam quae qui reiciendis sint quos repudiandae, accusantium repellendus voluptates consequatur tenetur animi blanditiis!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique error sint ullam et recusandae ex sapiente! Sit neque atque quisquam tempora dolorum praesentium. Laborum quibusdam voluptatum ipsum exercitationem recusandae, labore quod esse dolor cumque perspiciatis qui laudantium odio hic obcaecati, maiores velit ex unde, earum commodi? Expedita cumque dignissimos fuga libero sed dolorum nesciunt beatae deserunt, recusandae voluptatibus ratione doloremque repudiandae amet nisi dolor. Dolorum quo obcaecati ratione molestias dicta minima accusantium error sit libero! Dolores aut temporibus quibusdam iure deserunt dicta at perferendis exercitationem hic totam quae qui reiciendis sint quos repudiandae, accusantium repellendus voluptates consequatur tenetur animi blanditiis!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique error sint ullam et recusandae ex sapiente! Sit neque atque quisquam tempora dolorum praesentium. Laborum quibusdam voluptatum ipsum exercitationem recusandae, labore quod esse dolor cumque perspiciatis qui laudantium odio hic obcaecati, maiores velit ex unde, earum commodi? Expedita cumque dignissimos fuga libero sed dolorum nesciunt beatae deserunt, recusandae voluptatibus ratione doloremque repudiandae amet nisi dolor. Dolorum quo obcaecati ratione molestias dicta minima accusantium error sit libero! Dolores aut temporibus quibusdam iure deserunt dicta at perferendis exercitationem hic totam quae qui reiciendis sint quos repudiandae, accusantium repellendus voluptates consequatur tenetur animi blanditiis!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique error sint ullam et recusandae ex sapiente! Sit neque atque quisquam tempora dolorum praesentium. Laborum quibusdam voluptatum ipsum exercitationem recusandae, labore quod esse dolor cumque perspiciatis qui laudantium odio hic obcaecati, maiores velit ex unde, earum commodi? Expedita cumque dignissimos fuga libero sed dolorum nesciunt beatae deserunt, recusandae voluptatibus ratione doloremque repudiandae amet nisi dolor. Dolorum quo obcaecati ratione molestias dicta minima accusantium error sit libero! Dolores aut temporibus quibusdam iure deserunt dicta at perferendis exercitationem hic totam quae qui reiciendis sint quos repudiandae, accusantium repellendus voluptates consequatur tenetur animi blanditiis!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique error sint ullam et recusandae ex sapiente! Sit neque atque quisquam tempora dolorum praesentium. Laborum quibusdam voluptatum ipsum exercitationem recusandae, labore quod esse dolor cumque perspiciatis qui laudantium odio hic obcaecati, maiores velit ex unde, earum commodi? Expedita cumque dignissimos fuga libero sed dolorum nesciunt beatae deserunt, recusandae voluptatibus ratione doloremque repudiandae amet nisi dolor. Dolorum quo obcaecati ratione molestias dicta minima accusantium error sit libero! Dolores aut temporibus quibusdam iure deserunt dicta at perferendis exercitationem hic totam quae qui reiciendis sint quos repudiandae, accusantium repellendus voluptates consequatur tenetur animi blanditiis!</p>
        </div>
        </div>
    );
};

export default Home;